pipeline {
     agent {
        any {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                bat 'npm run build'
                bat 'npm start & sleep 1'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat 'kill $(cat .pidfile)'
            }
        }
    }
}
