pipeline {
     agent {
        any {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        def scannerHome = tool 'SonarScanner';
    }

    stages {
        /*
        stage('SCM') {
            steps {
                git url:'https://github.com/alexbertschi/simple-node-js-react-npm-app.git', branch:'main'
            }
        }

        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarScanner') { // If you have configured more than one global server connection, you can specify its name
                    bat "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
        */
        
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                bat 'npm run build'
                bat 'start npm run start'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
    }
}