pipeline {
     agent {
        any {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }

    stages {
          stage('SonarQube Analysis') {
            def scannerHome = tool 'SonarScanner';
            withSonarQubeEnv() {
            bat "${scannerHome}/bin/sonar-scanner"
            }
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                bat 'npm run build'
                bat 'start npm run start'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
    }
}
